Refactoring/create mainpage
HeXA-UNIST/hexa-homepage-frontend pull request #7
Opened 2023-01-19 11:28 UTC by gongbj0113

폴더 구조 수정, Redux 대신 MobX 사용 반영했습니다.

2023-01-21 10:44 UTC, SYChoi commented on src/App.jsx
> +            <Route path="/*" element={<Home />} />
지정되지 않은 주소로 접근했을 때 무조건 Home으로 가도록 하는게 맞을지 어떻게 처리할 지 다음 회의 때 논의해서 다시 처리하는게 필요해보임!

2023-01-21 10:48 UTC, SYChoi commented on src/pages/home/sections/News.jsx
> +import "static/css/home/Banner.css";
@css를 tsconfig에 넣어놨으니 `import "@css/home/Banner.css"` 라고 하는게 더 좋지 않았을까?

2023-01-21 10:49 UTC, SYChoi commented on src/pages/home/sections/Header.jsx
> +import profileimg from "static/img/profile_img.jpg";
`import "@img/profile_img.jpg";`

2023-01-21 10:50 UTC, SYChoi commented on src/pages/home/sections/Header.jsx
> +import "static/css/home/Header.css";
`import "@css/home/Header.css";`

2023-01-21 10:51 UTC, SYChoi commented on src/pages/home/sections/Banner.jsx
> +import "static/css/home/Banner.css";
`import "@css/home/Banner.css";`

2023-01-21 10:52 UTC, SYChoi commented on tsconfig.json
> +      "@page/*":["./src/pages/*"],
src/pages면 @pages라고 하는게 더 좋을거 같은데... 그래야 덜 헷갈릴듯

2023-01-21 10:53 UTC, SYChoi commented on tsconfig.json
> +      "@component/*" : ["./src/common/components/*"],
얘도 @components라고 하는게 좋지 않을까

2023-01-21 10:53 UTC, SYChoi commented on tsconfig.json
> +      "@model/*" : ["./src/models/*"],
@models라고 하자

2023-01-21 10:54 UTC, SYChoi commented on src/pages/home/sections/Supports.jsx
> +import "static/css/home/contents.css";
`import "@css/home/contents.css";`

2023-01-21 10:55 UTC, SYChoi commented on src/pages/home/index.jsx
> +import Header from "pages/home/sections/Header";
여기 안에도 싹 @pages/ 로 import 해오도록 수정해보자

2023-01-21 10:56 UTC, SYChoi commented on src/hooks/storeHooks.tsx
> +import LoginStore from "common/stores/LoginStore";
common도 많이 사용될텐데 @common으로 해서 import 해오도록 하면 좋지 않을까?

2023-01-21 10:56 UTC, SYChoi commented on src/common/stores/LoginStore.tsx
> +import IUser from "common/models/IUser";
여기도 common을 @common으로 가져오도록 수정

2023-01-21 10:58 UTC, SYChoi commented on src/common/models/IUser.tsx
> +export default interface IUser {
일단 db랑 동일하게 뽑아놓은거 같은데 반드시 같을 필요는 없기도 하고, api 형태에 따라 달라질 수도 있는거라서 보고 필요 없는 값이나 변동되는 것들은 나중에 바꾸면 될 것 같음

2023-01-21 11:01 UTC, SYChoi requested changes
기본 틀 잘 잡긴 했는데 적혀있는거처럼 파일 자체에도 @으로 import 해오지 않으면 tsconfig에 세팅해둔게 의미가 없으니 잘 적용해보는게 좋을 것 같음! 그 이외에는 앞으로 작업하다보면 수정되는거 보고 더 맞춰서 작업해가면 되는 것이니 보고 더 작업하는걸로...

2023-01-26 12:21 UTC, lafest reviewed
mobx는 저도 처음 접해봐서, 공부를 좀 해보고 다시 리뷰해볼게요.

2023-01-26 12:21 UTC, lafest commented on package.json
> +    "@babel/core": "^7.20.12",
babel은 [공식 가이드](https://babeljs.io/setup#installation)에서 `--save-dev`옵션을 통해 devDependencies로 받도록 가이드하고 있어요. 

devDependencies와 dependencies에 대한 차이는 [stackoverflow QnA](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
)를 참고하시면 좋을 것 같아요.

간략하게 요약하면..

devDependencies는 개발환경에서만 사용되고, 프로덕션 빌드 시에 제외되는 라이브러리들이에요. 그래서 타입스크립트와 관련된 타입 라이브러리, eslint 관련 라이브러리 등은 devDependencies에 등록하고 프로덕션 빌드에서는 실제 페이지 구현에 필요한 라이브러리들만 포함되게 하여 번들 사이즈를 줄이곤 합니다.

그리고 여기에서 바벨의 역할은 es6(Promise, async/await 등의 문법)로 짜여진 코드를 es5로 돌아가도록 하위호환된 코드로 변환해주는 것인데, 빌드 결과물은 결국 변환된 코드만을 이용하므로 바벨은 프로덕션 빌드에 포함되지 않아도 되어요.

2023-01-26 12:21 UTC, lafest commented on package.json
> +    "@babel/core": "^7.20.12",
마찬가지로 아래의 testing-library나 eslint plugin같은 라이브러리들은 devDependencies로 옮겨서 프로덕션 빌드의 번들 사이즈를 줄일 수 있을거에요.

2023-01-26 12:21 UTC, lafest commented on src/pages/home/sections/Footer.jsx
> -import React from "react";
일부 파일에는 `import React from "react";`가 남아있고 일부에는 빠져있는데, 통일하는 게 좋을 것 같습니다. [react 17부터 jsx파일에 `import React from "react";` 구문이 없어도 정상적으로 실행되도록 변경되었는데,](https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) 모든 곳에서 없애는 게 좋을 것 같아요.

2023-02-06 08:13 UTC, merged